# Generated by Django 3.1.14 on 2023-05-12 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herojAPI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bolest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime_bolesti', models.CharField(max_length=100)),
                ('opis_nacina_reagovanja', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Korisnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=50)),
                ('prezime', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pitanja',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('postavka', models.TextField()),
                ('tacan_odgovor', models.TextField()),
                ('tezina', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PredavanjeDokumentacija',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('naziv', models.CharField(max_length=255)),
                ('opis', models.TextField()),
                ('dokumentacija', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PredavanjeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naslov', models.CharField(max_length=100)),
                ('opis', models.TextField()),
                ('link_videa', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Simptom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simptom', models.CharField(max_length=100)),
                ('bolesti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herojAPI.bolest')),
            ],
        ),
        migrations.AddField(
            model_name='bolest',
            name='simptomi',
            field=models.ManyToManyField(to='herojAPI.Simptom'),
        ),
    ]
