# Generated by Django 3.1.14 on 2023-05-16 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herojAPI', '0002_auto_20230512_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='probna',
            name='author',
        ),
        migrations.RemoveField(
            model_name='simptom',
            name='bolesti',
        ),
        migrations.DeleteModel(
            name='Bolest',
        ),
        migrations.DeleteModel(
            name='Probna',
        ),
        migrations.DeleteModel(
            name='Simptom',
        ),
    ]
