# Generated by Django 3.1.14 on 2023-05-16 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herojAPI', '0003_auto_20230516_1145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nesrece',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vrsta', models.CharField(max_length=30)),
                ('opis', models.TextField()),
                ('korisnikid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herojAPI.korisnik')),
            ],
        ),
        migrations.CreateModel(
            name='RezultatiTestiranja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rezultat', models.BooleanField()),
                ('korisnikid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herojAPI.korisnik')),
            ],
        ),
        migrations.CreateModel(
            name='PostupciPrvePomoci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis', models.TextField()),
                ('nesreca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herojAPI.nesrece')),
            ],
        ),
        migrations.CreateModel(
            name='HistorijaNesreca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('korisnikid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herojAPI.korisnik')),
                ('nesreca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herojAPI.nesrece')),
            ],
        ),
    ]
