# Generated by Django 4.2.1 on 2023-05-18 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herojAPI', '0004_historijanesreca_nesrece_postupciprvepomoci_rezultatitestiranja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nesrece',
            name='korisnikid',
        ),
    ]
