# Generated by Django 4.2.1 on 2023-05-18 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herojAPI', '0006_nesrece_simptomi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Simptomi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('vrsta', models.CharField(max_length=50)),
                ('naziv', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='historijanesreca',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='korisnik',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='nesrece',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='postupciprvepomoci',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='predavanjevideo',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rezultatitestiranja',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Nesrece_Simptomi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nesreca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herojAPI.nesrece')),
                ('simptom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='herojAPI.simptomi')),
            ],
        ),
    ]
