# Generated by Django 4.2.1 on 2023-05-18 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herojAPI', '0007_simptomi_alter_historijanesreca_id_alter_korisnik_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nesrece',
            name='simptomi',
        ),
    ]
