# Generated by Django 4.2.1 on 2023-05-18 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herojAPI', '0008_remove_nesrece_simptomi'),
    ]

    operations = [
        migrations.CreateModel(
            name='Korisnik1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(max_length=100)),
                ('prezime', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('passW', models.CharField(max_length=500)),
            ],
        ),
    ]
