# Generated by Django 4.2.1 on 2023-05-21 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herojAPI', '0009_remove_predavanjedokumentacija_opis_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='predavanjevideo',
            name='opis',
        ),
    ]
