# Generated by Django 4.2.1 on 2023-05-24 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herojAPI', '0010_remove_predavanjevideo_opis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predavanjedokumentacija',
            name='dokumentacija',
            field=models.URLField(max_length=255),
        ),
    ]
