# Generated by Django 3.1.14 on 2023-05-27 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('herojAPI', '0010_auto_20230524_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historijanesreca',
            name='korisnikid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rezultatitestiranja',
            name='korisnikid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Korisnik1',
        ),
    ]
