# Generated by Django 3.1.14 on 2023-05-27 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herojAPI', '0011_auto_20230527_1706'),
        ('herojAPI', '0010_remove_predavanjevideo_opis'),
    ]

    operations = [
    ]
