# Generated by Django 3.1.14 on 2023-05-27 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herojAPI', '0012_merge_20230527_1813'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PredavanjeDokumentacija',
        ),
        migrations.DeleteModel(
            name='PredavanjeVideo',
        ),
    ]
