# Generated by Django 3.1.14 on 2023-05-30 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('herojAPI', '0014_nesrece_simptomi_prva_pomoc'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistorijaNesreca',
        ),
    ]
