# Generated by Django 3.1.14 on 2023-06-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herojAPI', '0015_delete_historijanesreca'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFFajlovi',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('naziv', models.CharField(max_length=50)),
                ('fajl', models.FileField(blank=True, upload_to='pdf-fajlovi/')),
                ('odobreno', models.BooleanField()),
            ],
        ),
    ]
