# Generated by Django 3.1.14 on 2023-06-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herojAPI', '0017_auto_20230601_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoPrimjeri',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('naslov', models.CharField(max_length=50)),
                ('link_videa', models.URLField()),
            ],
        ),
    ]
