# Generated by Django 3.1.14 on 2023-06-05 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('herojAPI', '0018_videoprimjeri'),
    ]

    operations = [
        migrations.CreateModel(
            name='Odgovori',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('odgovor', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='pitanja',
            name='netacan_odgovor1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pitanja_netacan1', to='herojAPI.odgovori'),
        ),
        migrations.AddField(
            model_name='pitanja',
            name='netacan_odgovor2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pitanja_netacan2', to='herojAPI.odgovori'),
        ),
        migrations.AlterField(
            model_name='pitanja',
            name='tacan_odgovor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pitanja_tacan', to='herojAPI.odgovori'),
        ),
    ]
